import c1 from '@/imports/CONUN_MGR-01.png'
import c2 from '@/imports/CONUN_MGR-02.png'
import c3 from '@/imports/CONUN_MGR-03.png'
import c4 from '@/imports/CONUN_MGR-04.png'
import c5 from '@/imports/CONUN_MGR-05.png'
import c6 from '@/imports/CONUN_MGR-06.png'
import c7 from '@/imports/CONUN_MGR-07.png'
import c8 from '@/imports/CONUN_MGR-08.png'
import wp1 from '@/imports/CyconWP_Port_2025.jpg'
import wp2 from '@/imports/CyconWP_Port_202516.jpg'
import wp3 from '@/imports/CyconWP_Port_202517.jpg'
import wp4 from '@/imports/CyconWP_Port_20252.jpg'
interface Props{navigate:(page:string)=>void}
const Gallery=({images,label}:{images:string[];label:string})=><div className="grid grid-cols-1 md:grid-cols-2 gap-4">{images.map((src,i)=><img key={i} src={src} alt={`${label} ${i+1}`} className="w-full h-auto"/>)}</div>
export default function ConunCyconProject({navigate}:Props){return <article className="page-enter"><section className="pt-36 pb-20 px-8 md:px-16" style={{backgroundColor:'var(--color-ink)'}}><div className="max-w-screen-xl mx-auto"><button onClick={()=>navigate('work')} className="text-xs tracking-[0.2em] uppercase mb-16 text-white/50">← Back to Work Index</button><p className="text-xs tracking-[0.25em] uppercase mb-4 text-white/50">UX/UI Design · South Korea · c. 2019–2020</p><h1 className="text-6xl md:text-8xl leading-none text-white" style={{fontFamily:'var(--font-display)'}}>Conun + Cycon<br/><em>UX/UI & Digital Design</em></h1></div></section><section className="py-24 px-8 md:px-16"><div className="max-w-screen-xl mx-auto grid md:grid-cols-12 gap-16"><div className="md:col-span-4 space-y-5">{[['Role','UX/UI Designer'],['Industry','Crypto / decentralized storage'],['Period','c. 2019–2020'],['Scope','Website, software concepts, white-paper design proposal']].map(([a,b])=><div key={a} className="border-b pb-4" style={{borderColor:'var(--color-border)'}}><p className="text-[10px] uppercase tracking-[0.2em]" style={{color:'var(--color-muted)'}}>{a}</p><p className="text-sm">{b}</p></div>)}</div><div className="md:col-span-7 md:col-start-6"><h2 className="text-4xl md:text-5xl mb-8" style={{fontFamily:'var(--font-display)'}}>Interface and publication concepts developed for an early-stage decentralized-storage company.</h2><p className="leading-relaxed mb-5" style={{color:'var(--color-muted)'}}>I worked as a UX/UI designer on Conun and related Cycon materials. My work included website design and interface concepts for software the company was testing. I left before those product concepts were completed or published.</p><p className="leading-relaxed" style={{color:'var(--color-muted)'}}>The Cycon white-paper pages shown here were design proposals I presented. They were not ultimately used by the company; the work was handed to another intern to continue.</p></div></div></section><section className="px-8 md:px-16 py-20" style={{backgroundColor:'var(--color-paper-dark)'}}><div className="max-w-screen-xl mx-auto"><h3 className="text-3xl md:text-4xl mb-8" style={{fontFamily:'var(--font-display)'}}>Conun Manager Interface Concepts</h3><Gallery images={[c1,c2,c3,c4,c5,c6,c7,c8]} label="Conun manager interface"/></div></section><section className="px-8 md:px-16 py-20"><div className="max-w-screen-xl mx-auto"><h3 className="text-3xl md:text-4xl mb-8" style={{fontFamily:'var(--font-display)'}}>Cycon White-Paper Design Proposal</h3><Gallery images={[wp1,wp2,wp3,wp4]} label="Cycon white paper design"/></div></section></article>}