import poster from '@/imports/Klingerhuf Restoration Event_Reel_01.png'
import carousel1 from '@/imports/ Klingerhuf Restoration Event_Carousel_001.png'

interface Props { navigate: (page: string) => void }

export default function KlingerhufProject({ navigate }: Props) {
  return <article className="page-enter">
    <section className="pt-36 pb-20 px-8 md:px-16" style={{backgroundColor:'var(--color-ink)'}}><div className="max-w-screen-xl mx-auto"><button onClick={()=>navigate('work')} className="text-xs tracking-[0.2em] uppercase mb-16 text-white/50">← Back to Work Index</button><p className="text-xs tracking-[0.25em] uppercase mb-4 text-white/50">Community Communication · Volunteer Activity · 2026</p><h1 className="text-6xl md:text-8xl leading-none text-white" style={{fontFamily:'var(--font-display)'}}>Klingerhuf Restoration<br/><em>Community Participation</em></h1></div></section>
    <section className="py-24 px-8 md:px-16"><div className="max-w-screen-xl mx-auto grid md:grid-cols-12 gap-16"><div className="md:col-span-4 space-y-5">{[['Role','Communication Design, Promotion, Volunteer Participation'],['Partner','Stay to Grow'],['Context','AStA HSRW community activity'],['Year','2026']].map(([a,b])=><div className="border-b pb-4" style={{borderColor:'var(--color-border)'}} key={a}><p className="text-[10px] uppercase tracking-[0.2em]" style={{color:'var(--color-muted)'}}>{a}</p><p className="text-sm">{b}</p></div>)}</div><div className="md:col-span-7 md:col-start-6"><h2 className="text-4xl md:text-5xl mb-8" style={{fontFamily:'var(--font-display)'}}>Communication design for a real community restoration activity.</h2><p className="leading-relaxed mb-5" style={{color:'var(--color-muted)'}}>The Klingerhuf restoration activity was organized in partnership with Stay to Grow. I did not organize the event itself. My contribution was to create the promotional graphics, help communicate the opportunity to students, and participate in the restoration as a volunteer.</p><p className="leading-relaxed" style={{color:'var(--color-muted)'}}>The visual work used photography to make the activity feel concrete and approachable, connecting the communication directly to the place and the volunteer experience.</p></div></div></section>
    <section className="px-8 md:px-16 pb-28"><div className="max-w-screen-xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-4"><img src={poster} alt="Klingerhuf restoration poster" className="w-full h-auto"/><img src={carousel1} alt="Klingerhuf restoration carousel image" className="w-full h-auto"/></div></section>
  </article>
}